package com.chinasofti.mms.pojo;

public class Counter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter.visitcount
     *
     * @mbggenerated Mon Jul 17 17:19:02 CST 2017
     */
    private Integer visitcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter.visitcount
     *
     * @return the value of counter.visitcount
     *
     * @mbggenerated Mon Jul 17 17:19:02 CST 2017
     */
    public Integer getVisitcount() {
        return visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter.visitcount
     *
     * @param visitcount the value for counter.visitcount
     *
     * @mbggenerated Mon Jul 17 17:19:02 CST 2017
     */
    public void setVisitcount(Integer visitcount) {
        this.visitcount = visitcount;
    }
}