package com.chinasofti.mms.pojo;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DepartmentId
     *
     * @mbggenerated Mon Jul 17 15:15:30 CST 2017
     */
    private Integer departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DepartmentName
     *
     * @mbggenerated Mon Jul 17 15:15:30 CST 2017
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.Remark
     *
     * @mbggenerated Mon Jul 17 15:15:30 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DepartmentId
     *
     * @return the value of department.DepartmentId
     *
     * @mbggenerated Mon Jul 17 15:15:30 CST 2017
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DepartmentId
     *
     * @param departmentid the value for department.DepartmentId
     *
     * @mbggenerated Mon Jul 17 15:15:30 CST 2017
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DepartmentName
     *
     * @return the value of department.DepartmentName
     *
     * @mbggenerated Mon Jul 17 15:15:30 CST 2017
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DepartmentName
     *
     * @param departmentname the value for department.DepartmentName
     *
     * @mbggenerated Mon Jul 17 15:15:30 CST 2017
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.Remark
     *
     * @return the value of department.Remark
     *
     * @mbggenerated Mon Jul 17 15:15:30 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.Remark
     *
     * @param remark the value for department.Remark
     *
     * @mbggenerated Mon Jul 17 15:15:30 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}