package com.chinasofti.mms.pojo;

public class MeetingParticipants {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingparticipants.mpId
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    private Integer mpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingparticipants.MeetingId
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    private Integer meetingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingparticipants.ParticipantId
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    private Integer participantid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingparticipants.mpId
     *
     * @return the value of meetingparticipants.mpId
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    public Integer getMpid() {
        return mpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingparticipants.mpId
     *
     * @param mpid the value for meetingparticipants.mpId
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    public void setMpid(Integer mpid) {
        this.mpid = mpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingparticipants.MeetingId
     *
     * @return the value of meetingparticipants.MeetingId
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    public Integer getMeetingid() {
        return meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingparticipants.MeetingId
     *
     * @param meetingid the value for meetingparticipants.MeetingId
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    public void setMeetingid(Integer meetingid) {
        this.meetingid = meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingparticipants.ParticipantId
     *
     * @return the value of meetingparticipants.ParticipantId
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    public Integer getParticipantid() {
        return participantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingparticipants.ParticipantId
     *
     * @param participantid the value for meetingparticipants.ParticipantId
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    public void setParticipantid(Integer participantid) {
        this.participantid = participantid;
    }
}