package com.chinasofti.mms.pojo;

public class MeetingRoom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.RoomId
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    private Integer roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.RoomCode
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    private String roomcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.RoomName
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    private String roomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.RoomCapacity
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    private Integer roomcapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.RoomStatus
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    private Integer roomstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.Description
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.RoomId
     *
     * @return the value of meetingroom.RoomId
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.RoomId
     *
     * @param roomid the value for meetingroom.RoomId
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.RoomCode
     *
     * @return the value of meetingroom.RoomCode
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public String getRoomcode() {
        return roomcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.RoomCode
     *
     * @param roomcode the value for meetingroom.RoomCode
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public void setRoomcode(String roomcode) {
        this.roomcode = roomcode == null ? null : roomcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.RoomName
     *
     * @return the value of meetingroom.RoomName
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public String getRoomname() {
        return roomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.RoomName
     *
     * @param roomname the value for meetingroom.RoomName
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public void setRoomname(String roomname) {
        this.roomname = roomname == null ? null : roomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.RoomCapacity
     *
     * @return the value of meetingroom.RoomCapacity
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public Integer getRoomcapacity() {
        return roomcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.RoomCapacity
     *
     * @param roomcapacity the value for meetingroom.RoomCapacity
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public void setRoomcapacity(Integer roomcapacity) {
        this.roomcapacity = roomcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.RoomStatus
     *
     * @return the value of meetingroom.RoomStatus
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public Integer getRoomstatus() {
        return roomstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.RoomStatus
     *
     * @param roomstatus the value for meetingroom.RoomStatus
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public void setRoomstatus(Integer roomstatus) {
        this.roomstatus = roomstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.Description
     *
     * @return the value of meetingroom.Description
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.Description
     *
     * @param description the value for meetingroom.Description
     *
     * @mbggenerated Mon Jul 17 14:36:31 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}