package com.chinasofti.mms.pojo;

import java.util.Date;

public class Meeting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.MeetingId
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private Integer meetingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.MeetingName
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private String meetingname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.RoomId
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private Integer roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.ReservationistId
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private Integer reservationistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.NumOfParticipants
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private Integer numofparticipants;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.BeginTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.EndTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.ReservationTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private Date reservationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.CanceledTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private Date canceledtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.MeetingStatus
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private Integer meetingstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.Description
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.MeetingId
     *
     * @return the value of meeting.MeetingId
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public Integer getMeetingid() {
        return meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.MeetingId
     *
     * @param meetingid the value for meeting.MeetingId
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setMeetingid(Integer meetingid) {
        this.meetingid = meetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.MeetingName
     *
     * @return the value of meeting.MeetingName
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public String getMeetingname() {
        return meetingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.MeetingName
     *
     * @param meetingname the value for meeting.MeetingName
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setMeetingname(String meetingname) {
        this.meetingname = meetingname == null ? null : meetingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.RoomId
     *
     * @return the value of meeting.RoomId
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.RoomId
     *
     * @param roomid the value for meeting.RoomId
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.ReservationistId
     *
     * @return the value of meeting.ReservationistId
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public Integer getReservationistid() {
        return reservationistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.ReservationistId
     *
     * @param reservationistid the value for meeting.ReservationistId
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setReservationistid(Integer reservationistid) {
        this.reservationistid = reservationistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.NumOfParticipants
     *
     * @return the value of meeting.NumOfParticipants
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public Integer getNumofparticipants() {
        return numofparticipants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.NumOfParticipants
     *
     * @param numofparticipants the value for meeting.NumOfParticipants
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setNumofparticipants(Integer numofparticipants) {
        this.numofparticipants = numofparticipants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.BeginTime
     *
     * @return the value of meeting.BeginTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.BeginTime
     *
     * @param begintime the value for meeting.BeginTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.EndTime
     *
     * @return the value of meeting.EndTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.EndTime
     *
     * @param endtime the value for meeting.EndTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.ReservationTime
     *
     * @return the value of meeting.ReservationTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public Date getReservationtime() {
        return reservationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.ReservationTime
     *
     * @param reservationtime the value for meeting.ReservationTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setReservationtime(Date reservationtime) {
        this.reservationtime = reservationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.CanceledTime
     *
     * @return the value of meeting.CanceledTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public Date getCanceledtime() {
        return canceledtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.CanceledTime
     *
     * @param canceledtime the value for meeting.CanceledTime
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setCanceledtime(Date canceledtime) {
        this.canceledtime = canceledtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.MeetingStatus
     *
     * @return the value of meeting.MeetingStatus
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public Integer getMeetingstatus() {
        return meetingstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.MeetingStatus
     *
     * @param meetingstatus the value for meeting.MeetingStatus
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setMeetingstatus(Integer meetingstatus) {
        this.meetingstatus = meetingstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.Description
     *
     * @return the value of meeting.Description
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.Description
     *
     * @param description the value for meeting.Description
     *
     * @mbg.generated Mon Jul 17 14:43:46 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}