package com.chinasofti.mms.dao;

import com.chinasofti.mms.pojo.Counter;

public interface CounterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter
     *
     * @mbggenerated Mon Jul 17 17:19:02 CST 2017
     */
    int insert(Counter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table counter
     *
     * @mbggenerated Mon Jul 17 17:19:02 CST 2017
     */
    int insertSelective(Counter record);
}