package com.chinasofti.mms.dao;

import com.chinasofti.mms.pojo.MeetingParticipants;

public interface MeetingParticipantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingparticipants
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    int deleteByPrimaryKey(Integer mpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingparticipants
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    int insert(MeetingParticipants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingparticipants
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    int insertSelective(MeetingParticipants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingparticipants
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    MeetingParticipants selectByPrimaryKey(Integer mpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingparticipants
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    int updateByPrimaryKeySelective(MeetingParticipants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingparticipants
     *
     * @mbggenerated Mon Jul 17 14:35:17 CST 2017
     */
    int updateByPrimaryKey(MeetingParticipants record);
}